### ISSUE TITLE
Arrangement of badges and share buttons

### ISSUE THREAD

**Issue by agahkarakuzu** [brainhack-proceedings/template#1]
Thank you @anibalsolon, adding this as an issue here, so we won't forget. 

> I would suggest keeping the badges together on the left, and the "share" buttons aligned to the right, without the "Share on" text, and in a darker gray.

**Comment by agahkarakuzu** [comment]
@anibalsolon https://brainhack-proceedings.github.io/template/ 

I did the changes, what do you think?

**Comment by anibalsolon** [comment]
@agahkarakuzu it looks great! thank you :)
